# Generated by Django 4.0.6 on 2022-07-22 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsAccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(default=None, max_length=255)),
                ('DOB', models.DateField(default=None)),
                ('date_admitted', models.DateField(default=None)),
                ('previous_School', models.CharField(default=None, max_length=255)),
                ('EntryScore', models.IntegerField(default=0)),
                ('comment', models.TextField(default=None, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
