# Generated by Django 4.0.6 on 2022-07-22 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsAccounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2022, 7, 22, 16, 36, 20, 443491)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_admitted',
            field=models.DateField(default=datetime.datetime(2022, 7, 22, 16, 36, 20, 443491)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_School',
            field=models.CharField(default='', max_length=255),
        ),
    ]
