# Generated by Django 4.0.6 on 2022-07-23 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsAccounts', '0003_alter_profile_dob_alter_profile_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 9, 3, 57, 610521)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_admitted',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 9, 3, 57, 610521)),
        ),
    ]
