# Generated by Django 4.0.6 on 2022-07-23 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsAccounts', '0004_alter_profile_dob_alter_profile_date_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 9, 58, 14, 129576)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_admitted',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 9, 58, 14, 129576)),
        ),
    ]
