# Generated by Django 4.0.6 on 2022-07-23 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsAccounts', '0008_alter_profile_dob_alter_profile_date_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 10, 6, 27, 702717)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_admitted',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 10, 6, 27, 702717)),
        ),
    ]
