# Generated by Django 4.0.6 on 2022-07-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classManagement', '0003_classmembersdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSelectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classManagement.classlist')),
                ('StudentRegNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classManagement.classmembersdetails')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectManagement.subjectlist')),
            ],
        ),
    ]
