# Generated by Django 4.0.6 on 2022-07-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=255, unique=True)),
                ('classTeacher', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classMemberReg', models.CharField(max_length=50)),
                ('className', models.ManyToManyField(to='classManagement.classlist')),
            ],
        ),
    ]
