# Generated by Django 4.0.6 on 2022-07-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, unique=True)),
                ('Teacher', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
