# Generated by Django 4.0.6 on 2022-07-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlist',
            old_name='className',
            new_name='classNames',
        ),
    ]
