# Generated by Django 4.0.6 on 2022-07-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classManagement', '0002_rename_names_classlist_classnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMembersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentReg', models.CharField(default=None, max_length=255)),
                ('ClassLevelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classManagement.classlist')),
            ],
        ),
    ]
