# Generated by Django 4.0.6 on 2022-07-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classManagement', '0003_rename_classname_classmembers_classnames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlist',
            old_name='classTeacher',
            new_name='classTeachers',
        ),
    ]
