# Generated by Django 4.0.6 on 2022-07-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classManagement', '0004_rename_classteacher_classlist_classteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='classTeachers',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='classmembers',
            name='classMemberReg',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
